# --- Site ---
title: "Истории"
description: "Короткие истории и заметки"
lang: ru-RU

# Для локалки можно оставить пустыми.
# Для GitHub Pages обычно:
# url: "https://USERNAME.github.io"
# baseurl: "/REPO"
url: ""
baseurl: ""

# --- Theme ---
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "air"   # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"  [web:696]

# --- Build ---
markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

teaser: /assets/images/teaser.jpg
